package:
  name: corrfunc
  version: "0.2.1"

source:
  path: dist
  fn: Corrfunc-0.2.1.tar.gz
  md5: 54e2b777517f074847f11223344a1577

  # fn: Corrfunc-0.2.1.tar.gz
  # url: https://github.com/manodeep/Corrfunc/archive/0.2.1.tar.gz
  # md5: 2bd15dac1706cb59b5ddb528cd5c7db2

requirements:
  build:
    - python
    - numpy
    - setuptools 

  run:
    - python
    - numpy

build:
  detect_binary_files_with_prefix: True
  script: make install && python setup.py install 
  binary_relocation: True
  skip: True #[win]
  
test:
  files:
    - xi_theory/tests/data/gals_Mr19.ff
    - xi_mocks/tests/data/Mr19_mock_northonly.rdcz.dat
    - include/countpairs.h
    - include/countpairs_rp_pi_mocks.h
    - xi_theory/tests/bins
    - xi_mocks/tests/bins
    - xi_mocks/tests/angular_bins
    - xi_mocks/tests/data/Mr19_centers_xyz_forVPF_rmax_10Mpc.txt
  imports:
    - Corrfunc
    - Corrfunc._countpairs
    - Corrfunc._countpairs_mocks
    - Corrfunc.call_correlation_functions
    - Corrfunc.call_correlation_functions_mocks

  commands:
    - python -c "import Corrfunc.call_correlation_functions as c; c.main()"
    - python -c "import Corrfunc.call_correlation_functions_mocks as m; m.main()"
	
about:
  home: http://manodeep.github.io/Corrfunc/
  license: MIT
  license_file: LICENSE
  summary: Blazing fast correlation functions on the CPU
  
extra:
  maintainers:
    - Manodeep Sinha <manodeep@gmail.com>
    
    
